title: Adam's Github Learning Blog
author: Adam Ashby
email: adam.ashby@edf-energy.com
description: > # this means to ignore newlines until "baseurl:"
  This is what I will have learnt

# social links
twitter_username: mradamashby # DO NOT include the @ character, or else the build will fail!
github_username:  adamashbyedf # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
